let singleDigitNumber = Math.floor(Math.random() * 10) % 10;
if(singleDigitNumber==0)
    console.log("1. Zero")
else if(singleDigitNumber==1)
    console.log("1. One")
else if(singleDigitNumber==2)
    console.log("1. Two")
else if(singleDigitNumber==3)
    console.log("1. Three")
else if(singleDigitNumber==4)
    console.log("1. Four")
else if(singleDigitNumber==5)
    console.log("1. Five")
else if(singleDigitNumber==6)
    console.log("1. Six")
else if(singleDigitNumber==7)
    console.log("1. Seven")
else if(singleDigitNumber==8)
    console.log("1. Eight")
else
    console.log("1. Nine")