let weekNumber = Math.floor(Math.random() * 7) % 7 + 1;
if(weekNumber==1)
    console.log("2. Monday")
else if(weekNumber==2)
    console.log("2. Tuesday")
else if(weekNumber==3)
    console.log("2. Wednesday")
else if(weekNumber==4)
    console.log("2. Thursday")
else if(weekNumber==5)
    console.log("2. Friday")
else if(weekNumber==6)
    console.log("2. Saturday")
else
    console.log("2. Sunday")